### ISSUE TITLE
v6.1.6: composer.json is missing wallee/sdk dependency

### ISSUE THREAD

**Issue by cundd** [wallee-payment/shopware-6#18]
Commit https://github.com/wallee-payment/shopware-6/commit/bec06d582cebc63b00cb09c0036a064bf74a82a7#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34 and the accompanying release 6.1.6 remove the dependencies on `shopware/core`, `shopware/storefront` and `wallee/sdk`. 

With this change, installation and update via composer will not work anymore. Is there something missing in the installation instructions? E.g. do we have to specify the dependency and version constraints for `wallee/sdk` manually?

For reference: the same issue appeared with other wallee-based projects:
- https://github.com/weareplanet/shopware-6/issues/4
- https://github.com/pfpayments/shopware-6/commit/d8374f74a51af4c81a9452c86652608ec2b6fbe4#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34

**Comment by BStadlerWallee** [comment]
Dear cundd,

just informing you that our dev-team has opened an according bug-report for this and is already working on this on the current sprint, which means we should be able to give more details about it within the next 3 weeks.
We will get back to you directly once the case has updated.

Kind Regards
Wallee Support

**Comment by BStadlerWallee** [comment]
Dear Cundd,

our dev-team has further planned this case in to be analyzed more thoroughly until October.
We will keep you up to date about this will let you know about all further steps.

Kind Regards
Wallee Support

**Comment by BStadlerWallee** [comment]
Dear cundd,

I can gladly inform you, that we have finished fixing these issues that you have reported here in this case.
This includes the Shopware 6 composer files as well as conflicting requirements.
We have published a new version with these changes, which can be downloaded right away here:
https://github.com/wallee-payment/shopware-6

We will also close the support case on our end fo now.
If you have any questions, you can contact us again either here or directly via mail on info@wallee.com, including the case number 310146.

Kind Regards
Wallee Support

**Comment by cundd** [comment]
Great! The Composer installation now worked.

Can you tell me what the issues has been?

**Comment by BStadlerWallee** [comment]
Dear Cundd,

the issue were general problems within the requirements and basically what you have already reported us here.
The installation should be fine now.

Of course we stay available if you have any further questions.

Kind Regards
Wallee Support
