### ISSUE TITLE
saleschannel product comparison has payment config in wallee

### ISSUE THREAD

**Issue by nopzdk** [wallee-payment/shopware-6#3]
A product comparison channel does not have payment options when creating it, when installing wallee it creates payment options for product comparison channels.
the plugin should check for type of saleschannel and not create a configuration for saleschannels of type product comparison.

**Comment by andrewrowanwallee** [comment]
> A product comparison channel does not have payment options when creating it, when installing wallee it creates payment options for product comparison channels.
> the plugin should check for type of saleschannel and not create a configuration for saleschannels of type product comparison.

Could you provide a few more details about how to reproduce this error? Would you also be able to provide any details around potential issues it's causing for you? Many thanks

**Comment by vttn** [comment]
@nopzdk we are closing the issue for now. If you have more information please leave a comment.
