### ISSUE TITLE
Missing translations in permissions section

### ISSUE THREAD

**Issue by Isengo1989** [wallee-payment/shopware-6#5]
![2022-09-21_07-29](https://user-images.githubusercontent.com/8600299/191422069-f4503516-8945-4b57-88d9-8fa0e331bc07.png)

See image

**Comment by theodorspringwallee** [comment]
Dear [Isengo1989](https://github.com/Isengo1989)

On which Shopware 6 menu you have found this missing label?

Best regards

**Comment by Isengo1989** [comment]
@theodorspringwallee 
![image](https://user-images.githubusercontent.com/8600299/192449396-33f96517-c84d-484f-baa3-7485cc37f038.png)

/admin#/sw/users/permissions/index

then choose a role and scroll down:

/admin#/sw/users/permissions/role.detail/6180487019034a4ab27843b8cbd02666/general
